---------------------------------------------------------------------------------------------------------------
# Summary
---------------------------------------------------------------------------------------------------------------
## Content Log
1. Import Libraries
2. Load Data
3. Combined Datasets Summary
4. Combined Datasets Price Summary
5. Combined Datasets Movements Summary
6. Combined Datasets Volatility Summary
7. Final Datasets merged Summary
---------------------------------------------------------------------------------------------------------------

# 01. Import Libraries

In [1]:
import os
import pandas as pd
import numpy as np

# 02. Load Data

In [2]:
data_path = "../../data/raw_data"
datasets = {}
for file in os.listdir(data_path):
    if file.endswith(".csv"):
        df = pd.read_csv(os.path.join(data_path, file))
        df["Ticker"] = file.replace(".csv", "")
        datasets[file] = df
print(f"Total datasets loaded: {len(datasets)}")

Total datasets loaded: 30

# 03. Combined Datasets Summary

In [3]:
summary_list = []
for name, df in datasets.items():
    info = {
        "Dataset": name,
        "Rows": df.shape[0],
        "Columns": df.shape[1],
        "Start_Date": df["Date"].min() if "Date" in df.columns else None,
        "End_Date": df["Date"].max() if "Date" in df.columns else None,
        "Columns_Names": list(df.columns)
    }
    summary_list.append(info)
summary_df = pd.DataFrame(summary_list)
summary_df

,Dataset,Rows,Columns,Start_Date,End_Date,Columns_Names
0,ADANIENT_NS.csv,2470,7,1/1/2018,9/9/2025,"[Date, Close, High, Low, Open, Volume, Ticker]"
1,ADANIPORTS_NS.csv,2470,7,1/1/2018,9/9/2025,"[Date, Close, High, Low, Open, Volume, Ticker]"
2,ASIANPAINT_NS.csv,2470,7,1/1/2018,9/9/2025,"[Date, Close, High, Low, Open, Volume, Ticker]"
3,AXISBANK_NS.csv,2470,7,1/1/2018,9/9/2025,"[Date, Close, High, Low, Open, Volume, Ticker]"
4,BAJAJFINSV_NS.csv,2470,7,1/1/2018,9/9/2025,"[Date, Close, High, Low, Open, Volume, Ticker]"
5,BAJFINANCE_NS.csv,2470,7,1/1/2018,9/9/2025,"[Date, Close, High, Low, Open, Volume, Ticker]"
6,BHARTIARTL_NS.csv,2470,7,1/1/2018,9/9/2025,"[Date, Close, High, Low, Open, Volume, Ticker]"
7,DRREDDY_NS.csv,2470,7,1/1/2018,9/9/2025,"[Date, Close, High, Low, Open, Volume, Ticker]"
8,EICHERMOT_NS.csv,2470,7,1/1/2018,9/9/2025,"[Date, Close, High, Low, Open, Volume, Ticker]"
9,HCLTECH_NS.csv,2470,7,1/1/2018,9/9/2025,"[Date, Close, High, Low, Open, Volume, Ticker]"
10,HDFCBANK_NS.csv,2470,7,1/1/2018,9/9/2025,"[Date, Close, High, Low, Open, Volume, Ticker]"
11,HINDUNILVR_NS.csv,2470,7,1/1/2018,9/9/2025,"[Date, Close, High, Low, Open, Volume, Ticker]"
12,ICICIBANK_NS.csv,2470,7,1/1/2018,9/9/2025,"[Date, Close, High, Low, Open, Volume, Ticker]"
13,INFY_NS.csv,2470,7,1/1/2018,9/9/2025,"[Date, Close, High, Low, Open, Volume, Ticker]"
14,ITC_NS.csv,2470,7,1/1/2018,9/9/2025,"[Date, Close, High, Low, Open, Volume, Ticker]"
15,KOTAKBANK_NS.csv,2470,7,1/1/2018,9/9/2025,"[Date, Close, High, Low, Open, Volume, Ticker]"
16,LT_NS.csv,2470,7,1/1/2018,9/9/2025,"[Date, Close, High, Low, Open, Volume, Ticker]"
17,MARUTI_NS.csv,2470,7,1/1/2018,9/9/2025,"[Date, Close, High, Low, Open, Volume, Ticker]"
18,NESTLEIND_NS.csv,2470,7,1/1/2018,9/9/2025,"[Date, Close, High, Low, Open, Volume, Ticker]"
19,NTPC_NS.csv,2470,7,1/1/2018,9/9/2025,"[Date, Close, High, Low, Open, Volume, Ticker]"
20,ONGC_NS.csv,2470,7,1/1/2018,9/9/2025,"[Date, Close, High, Low, Open, Volume, Ticker]"
21,POWERGRID_NS.csv,2470,7,1/1/2018,9/9/2025,"[Date, Close, High, Low, Open, Volume, Ticker]"
22,RELIANCE_NS.csv,2470,7,1/1/2018,9/9/2025,"[Date, Close, High, Low, Open, Volume, Ticker]"
23,SBIN_NS.csv,2470,7,1/1/2018,9/9/2025,"[Date, Close, High, Low, Open, Volume, Ticker]"
24,SUNPHARMA_NS.csv,2470,7,1/1/2018,9/9/2025,"[Date, Close, High, Low, Open, Volume, Ticker]"
25,TCS_NS.csv,2470,7,1/1/2018,9/9/2025,"[Date, Close, High, Low, Open, Volume, Ticker]"
26,TECHM_NS.csv,2470,7,1/1/2018,9/9/2025,"[Date, Close, High, Low, Open, Volume, Ticker]"
27,TITAN_NS.csv,2470,7,1/1/2018,9/9/2025,"[Date, Close, High, Low, Open, Volume, Ticker]"
28,ULTRACEMCO_NS.csv,2470,7,1/1/2018,9/9/2025,"[Date, Close, High, Low, Open, Volume, Ticker]"
29,WIPRO_NS.csv,2470,7,1/1/2018,9/9/2025,"[Date, Close, High, Low, Open, Volume, Ticker]"

# 04. Combined Datasets Price Summary

In [4]:
market_summary = []
for name, df in datasets.items():
    stats = {
        "Dataset": name,
        "Mean_Close": df["Close"].mean() if "Close" in df.columns else None,
        "Std_Close": df["Close"].std() if "Close" in df.columns else None,
        "Min_Close": df["Close"].min() if "Close" in df.columns else None,
        "Max_Close": df["Close"].max() if "Close" in df.columns else None,
        "Avg_Volume": df["Volume"].mean() if "Volume" in df.columns else None
    }
    market_summary.append(stats)
market_summary_df = pd.DataFrame(market_summary)
market_summary_df

,Dataset,Mean_Close,Std_Close,Min_Close,Max_Close,Avg_Volume
0,ADANIENT_NS.csv,1269.420366,1226.836184,32.906822,4159.593750,6.127435e+06
1,ADANIPORTS_NS.csv,673.903555,405.764944,163.255951,1582.451172,5.501982e+06
2,ASIANPAINT_NS.csv,2082.829187,832.501464,779.422729,3460.254883,1.309598e+06
3,AXISBANK_NS.csv,765.932800,256.591634,301.889465,1403.000000,1.131986e+07
4,BAJAJFINSV_NS.csv,1099.777283,585.676827,163.690888,2176.600098,2.819291e+06
5,BAJFINANCE_NS.csv,483.026241,276.953166,60.086472,1094.150024,1.869561e+07
6,BHARTIARTL_NS.csv,748.172044,531.292995,248.379013,2162.699951,8.985938e+06
7,DRREDDY_NS.csv,821.713162,298.892306,358.653473,1403.588257,3.209322e+06
8,EICHERMOT_NS.csv,3088.422543,1393.885182,1208.917725,8190.000000,8.701461e+05
9,HCLTECH_NS.csv,818.543752,471.691867,270.814392,1908.191528,3.910370e+06
10,HDFCBANK_NS.csv,624.843365,201.654459,231.546707,1012.900024,1.937598e+07
11,HINDUNILVR_NS.csv,1871.275023,601.593625,682.621094,2939.454590,1.770625e+06
12,ICICIBANK_NS.csv,664.492658,390.609187,181.544952,1477.201782,1.846460e+07
13,INFY_NS.csv,1021.420114,492.752058,346.069702,1942.221191,8.080513e+06
14,ITC_NS.csv,251.849168,102.262508,107.234131,476.588745,1.717068e+07
15,KOTAKBANK_NS.csv,306.276594,84.918065,126.536163,453.237457,1.765321e+07
16,LT_NS.csv,1866.018199,1047.452810,648.860535,4418.100098,2.668586e+06
17,MARUTI_NS.csv,8280.942950,2893.682091,3132.276367,17292.000000,7.044838e+05
18,NESTLEIND_NS.csv,772.338975,336.208387,220.951584,1355.930542,1.509265e+06
19,NTPC_NS.csv,160.720419,101.687435,59.543129,425.839874,1.351703e+07
20,ONGC_NS.csv,132.942932,62.537150,40.190529,307.873627,1.517576e+07
21,POWERGRID_NS.csv,136.448917,84.820852,48.135250,344.843262,1.435302e+07
22,RELIANCE_NS.csv,870.386834,420.060484,203.784943,1592.300049,1.785488e+07
23,SBIN_NS.csv,438.368651,236.487555,139.191803,1227.800049,2.427468e+07
24,SUNPHARMA_NS.csv,864.952243,463.393059,305.600525,1918.210327,4.892554e+06
25,TCS_NS.csv,2383.258626,986.674190,844.116272,4311.585449,2.731429e+06
26,TECHM_NS.csv,863.320902,430.918767,278.204041,1768.400024,2.869909e+06
27,TITAN_NS.csv,1875.105931,1175.351779,293.463013,4342.600098,1.793651e+06
28,ULTRACEMCO_NS.csv,6421.062767,2997.977953,2790.100586,13052.000000,3.843714e+05
29,WIPRO_NS.csv,170.715304,70.334159,74.470154,333.296661,1.329176e+07

# 05. Combined Datasets Movements Summary

In [5]:
movement_summary = []
for name, df in datasets.items():
    if "Close" in df.columns:
        df_sorted = df.sort_values("Date")
        df_sorted["Next_Close"] = df_sorted["Close"].shift(-1)
        df_sorted["Movement"] = np.where(
            df_sorted["Next_Close"] > df_sorted["Close"], "UP", "DOWN"
        )
        up_ratio = (df_sorted["Movement"] == "UP").mean()
        down_ratio = (df_sorted["Movement"] == "DOWN").mean()
        movement_summary.append({
            "Dataset": name,
            "UP_Ratio": up_ratio,
            "DOWN_Ratio": down_ratio
        })
movement_df = pd.DataFrame(movement_summary)
movement_df

              Dataset  UP_Ratio  DOWN_Ratio
0     ADANIENT_NS.csv  0.672470    0.327530
1   ADANIPORTS_NS.csv  0.602429    0.397571
2   ASIANPAINT_NS.csv  0.631984    0.368016
3     AXISBANK_NS.csv  0.644130    0.355870
4   BAJAJFINSV_NS.csv  0.695547    0.304453
5   BAJFINANCE_NS.csv  0.714980    0.285020
6   BHARTIARTL_NS.csv  0.753036    0.246964
7      DRREDDY_NS.csv  0.570445    0.429555
8    EICHERMOT_NS.csv  0.629960    0.370040
9      HCLTECH_NS.csv  0.732389    0.267611
10    HDFCBANK_NS.csv  0.717814    0.282186
11  HINDUNILVR_NS.csv  0.674089    0.325911
12   ICICIBANK_NS.csv  0.793522    0.206478
13        INFY_NS.csv  0.618219    0.381781
14         ITC_NS.csv  0.599190    0.400810
15   KOTAKBANK_NS.csv  0.648988    0.351012
16          LT_NS.csv  0.714980    0.285020
17      MARUTI_NS.csv  0.654251    0.345749
18   NESTLEIND_NS.csv  0.755466    0.244534
19        NTPC_NS.csv  0.586640    0.413360
20        ONGC_NS.csv  0.516599    0.483401
21   POWERGRID_NS.csv  0.661134    0.338866
22    RELIANCE_NS.csv  0.740486    0.259514
23        SBIN_NS.csv  0.659919    0.340081
24   SUNPHARMA_NS.csv  0.572470    0.427530
25         TCS_NS.csv  0.645344    0.354656
26       TECHM_NS.csv  0.659514    0.340486
27       TITAN_NS.csv  0.769231    0.230769
28  ULTRACEMCO_NS.csv  0.653036    0.346964
29       WIPRO_NS.csv  0.591903    0.408097

# 06. Combined Datasets Volatility Summary

In [6]:
volatility_summary = []
for name, df in datasets.items():
    if "Close" in df.columns:
        returns = df["Close"].pct_change()
        volatility = returns.std()

        volatility_summary.append({
            "Dataset": name,
            "Volatility": volatility
        })

volatility_df = pd.DataFrame(volatility_summary)
volatility_df.sort_values(by="Volatility", ascending=False)

              Dataset  Volatility
0     ADANIENT_NS.csv    0.031952
1   ADANIPORTS_NS.csv    0.023279
5   BAJFINANCE_NS.csv    0.022370
20        ONGC_NS.csv    0.020829
4   BAJAJFINSV_NS.csv    0.020468
23        SBIN_NS.csv    0.020293
3     AXISBANK_NS.csv    0.020189
8    EICHERMOT_NS.csv    0.019068
12   ICICIBANK_NS.csv    0.018761
27       TITAN_NS.csv    0.018423
6   BHARTIARTL_NS.csv    0.018319
26       TECHM_NS.csv    0.018304
24   SUNPHARMA_NS.csv    0.017301
17      MARUTI_NS.csv    0.017203
22    RELIANCE_NS.csv    0.016942
13        INFY_NS.csv    0.016624
16          LT_NS.csv    0.016525
28  ULTRACEMCO_NS.csv    0.016445
29       WIPRO_NS.csv    0.016381
9      HCLTECH_NS.csv    0.016370
19        NTPC_NS.csv    0.016274
15   KOTAKBANK_NS.csv    0.016258
7      DRREDDY_NS.csv    0.016132
21   POWERGRID_NS.csv    0.015894
2   ASIANPAINT_NS.csv    0.015266
14         ITC_NS.csv    0.015127
25         TCS_NS.csv    0.014874
10    HDFCBANK_NS.csv    0.014122
18   NESTLEIND_NS.csv    0.013933
11  HINDUNILVR_NS.csv    0.013691

# 07. Final Datasets merged Summary

In [7]:
final_summary = summary_df.merge(market_summary_df, on="Dataset", how="left")
final_summary = final_summary.merge(movement_df, on="Dataset", how="left")
final_summary = final_summary.merge(volatility_df, on="Dataset", how="left")
final_summary

,Dataset,Rows,Columns,Start_Date,End_Date,Columns_Names,Mean_Close,Std_Close,Min_Close,Max_Close,Avg_Volume,UP_Ratio,DOWN_Ratio,Volatility
0,ADANIENT_NS.csv,2470,7,1/1/2018,9/9/2025,"[Date, Close, High, Low, Open, Volume, Ticker]",1269.420366,1226.836184,32.906822,4159.593750,6.127435e+06,0.672470,0.327530,0.031952
1,ADANIPORTS_NS.csv,2470,7,1/1/2018,9/9/2025,"[Date, Close, High, Low, Open, Volume, Ticker]",673.903555,405.764944,163.255951,1582.451172,5.501982e+06,0.602429,0.397571,0.023279
2,ASIANPAINT_NS.csv,2470,7,1/1/2018,9/9/2025,"[Date, Close, High, Low, Open, Volume, Ticker]",2082.829187,832.501464,779.422729,3460.254883,1.309598e+06,0.631984,0.368016,0.015266
3,AXISBANK_NS.csv,2470,7,1/1/2018,9/9/2025,"[Date, Close, High, Low, Open, Volume, Ticker]",765.932800,256.591634,301.889465,1403.000000,1.131986e+07,0.644130,0.355870,0.020189
4,BAJAJFINSV_NS.csv,2470,7,1/1/2018,9/9/2025,"[Date, Close, High, Low, Open, Volume, Ticker]",1099.777283,585.676827,163.690888,2176.600098,2.819291e+06,0.695547,0.304453,0.020468
5,BAJFINANCE_NS.csv,2470,7,1/1/2018,9/9/2025,"[Date, Close, High, Low, Open, Volume, Ticker]",483.026241,276.953166,60.086472,1094.150024,1.869561e+07,0.714980,0.285020,0.022370
6,BHARTIARTL_NS.csv,2470,7,1/1/2018,9/9/2025,"[Date, Close, High, Low, Open, Volume, Ticker]",748.172044,531.292995,248.379013,2162.699951,8.985938e+06,0.753036,0.246964,0.018319
7,DRREDDY_NS.csv,2470,7,1/1/2018,9/9/2025,"[Date, Close, High, Low, Open, Volume, Ticker]",821.713162,298.892306,358.653473,1403.588257,3.209322e+06,0.570445,0.429555,0.016132
8,EICHERMOT_NS.csv,2470,7,1/1/2018,9/9/2025,"[Date, Close, High, Low, Open, Volume, Ticker]",3088.422543,1393.885182,1208.917725,8190.000000,8.701461e+05,0.629960,0.370040,0.019068
9,HCLTECH_NS.csv,2470,7,1/1/2018,9/9/2025,"[Date, Close, High, Low, Open, Volume, Ticker]",818.543752,471.691867,270.814392,1908.191528,3.910370e+06,0.732389,0.267611,0.016370
10,HDFCBANK_NS.csv,2470,7,1/1/2018,9/9/2025,"[Date, Close, High, Low, Open, Volume, Ticker]",624.843365,201.654459,231.546707,1012.900024,1.937598e+07,0.717814,0.282186,0.014122
11,HINDUNILVR_NS.csv,2470,7,1/1/2018,9/9/2025,"[Date, Close, High, Low, Open, Volume, Ticker]",1871.275023,601.593625,682.621094,2939.454590,1.770625e+06,0.674089,0.325911,0.013691
12,ICICIBANK_NS.csv,2470,7,1/1/2018,9/9/2025,"[Date, Close, High, Low, Open, Volume, Ticker]",664.492658,390.609187,181.544952,1477.201782,1.846460e+07,0.793522,0.206478,0.018761
13,INFY_NS.csv,2470,7,1/1/2018,9/9/2025,"[Date, Close, High, Low, Open, Volume, Ticker]",1021.420114,492.752058,346.069702,1942.221191,8.080513e+06,0.618219,0.381781,0.016624
14,ITC_NS.csv,2470,7,1/1/2018,9/9/2025,"[Date, Close, High, Low, Open, Volume, Ticker]",251.849168,102.262508,107.234131,476.588745,1.717068e+07,0.599190,0.400810,0.015127
15,KOTAKBANK_NS.csv,2470,7,1/1/2018,9/9/2025,"[Date, Close, High, Low, Open, Volume, Ticker]",306.276594,84.918065,126.536163,453.237457,1.765321e+07,0.648988,0.351012,0.016258
16,LT_NS.csv,2470,7,1/1/2018,9/9/2025,"[Date, Close, High, Low, Open, Volume, Ticker]",1866.018199,1047.452810,648.860535,4418.100098,2.668586e+06,0.714980,0.285020,0.016525
17,MARUTI_NS.csv,2470,7,1/1/2018,9/9/2025,"[Date, Close, High, Low, Open, Volume, Ticker]",8280.942950,2893.682091,3132.276367,17292.000000,7.044838e+05,0.654251,0.345749,0.017203
18,NESTLEIND_NS.csv,2470,7,1/1/2018,9/9/2025,"[Date, Close, High, Low, Open, Volume, Ticker]",772.338975,336.208387,220.951584,1355.930542,1.509265e+06,0.755466,0.244534,0.013933
19,NTPC_NS.csv,2470,7,1/1/2018,9/9/2025,"[Date, Close, High, Low, Open, Volume, Ticker]",160.720419,101.687435,59.543129,425.839874,1.351703e+07,0.586640,0.413360,0.016274
20,ONGC_NS.csv,2470,7,1/1/2018,9/9/2025,"[Date, Close, High, Low, Open, Volume, Ticker]",132.942932,62.537150,40.190529,307.873627,1.517576e+07,0.516599,0.483401,0.020829
21,POWERGRID_NS.csv,2470,7,1/1/2018,9/9/2025,"[Date, Close, High, Low, Open, Volume, Ticker]",136.448917,84.820852,48.135250,344.843262,1.435302e+07,0.661134,0.338866,0.015894
22,RELIANCE_NS.csv,2470,7,1/1/2018,9/9/2025,"[Date, Close, High, Low, Open, Volume, Ticker]",870.386834,420.060484,203.784943,1592.300049,1.785488e+07,0.740486,0.259514,0.016942
23,SBIN_NS.csv,2470,7,1/1/2018,9/9/2025,"[Date, Close, High, Low, Open, Volume, Ticker]",438.368651,236.487555,139.191803,1227.800049,2.427468e+07,0.659919,0.340081,0.020293
24,SUNPHARMA_NS.csv,2470,7,1/1/2018,9/9/2025,"[Date, Close, High, Low, Open, Volume, Ticker]",864.952243,463.393059,305.600525,1918.210327,4.892554e+06,0.572470,0.427530,0.017301
25,TCS_NS.csv,2470,7,1/1/2018,9/9/2025,"[Date, Close, High, Low, Open, Volume, Ticker]",2383.258626,986.674190,844.116272,4311.585449,2.731429e+06,0.645344,0.354656,0.014874
26,TECHM_NS.csv,2470,7,1/1/2018,9/9/2025,"[Date, Close, High, Low, Open, Volume, Ticker]",863.320902,430.918767,278.204041,1768.400024,2.869909e+06,0.659514,0.340486,0.018304
27,TITAN_NS.csv,2470,7,1/1/2018,9/9/2025,"[Date, Close, High, Low, Open, Volume, Ticker]",1875.105931,1175.351779,293.463013,4342.600098,1.793651e+06,0.769231,0.230769,0.018423
28,ULTRACEMCO_NS.csv,2470,7,1/1/2018,9/9/2025,"[Date, Close, High, Low, Open, Volume, Ticker]",6421.062767,2997.977953,2790.100586,13052.000000,3.843714e+05,0.653036,0.346964,0.016445
29,WIPRO_NS.csv,2470,7,1/1/2018,9/9/2025,"[Date, Close, High, Low, Open, Volume, Ticker]",170.715304,70.334159,74.470154,333.296661,1.329176e+07,0.591903,0.408097,0.016381